Repository TerryCavanagh/VVVVVV, pull requests merged in 2023-02, with the labels that each got.

#926 Fix screen shake during flip mode not flipping the screen
  desktop_version/src/Graphics.cpp
Labels: required for 2.4

#910 Custom textbox colors
  desktop_version/src/BlockV.cpp
  desktop_version/src/CustomLevels.cpp
  desktop_version/src/CustomLevels.h
  desktop_version/src/Script.cpp
Labels: enhancement, targets 2.4

#931 Add magic string to the start of the `game` global
  desktop_version/src/Game.cpp
  desktop_version/src/Game.h
Labels: required for 2.4

#935 Update Esperanto translation
  desktop_version/lang/eo/strings.xml
  desktop_version/lang/eo/strings_plural.xml
Labels: localization
