Repository TerryCavanagh/VVVVVV, pull requests merged in 2023-08, with the labels that each got.

#990 Controller layout detection
  desktop_version/src/ButtonGlyphs.cpp
  desktop_version/src/ButtonGlyphs.h
  desktop_version/src/KeyPoll.cpp
Labels: required for 2.4

#995 Fix UB where image loading fails in certain cases
  desktop_version/src/GraphicsResources.cpp
Labels: required for 2.4

#908 Terminal edentity tweaks
  desktop_version/src/Map.cpp
Labels: enhancement, targets 2.4

#996 Adjust lab autotiling
  desktop_version/src/Editor.cpp
Labels: enhancement, targets 2.4

#998 Change editor unsupported message to only appear when editor is selected
  desktop_version/src/Render.cpp
Labels: required for 2.4

#1000 Fix `setfont()` changing font of fading out text boxes
  desktop_version/src/Script.cpp
Labels: localization
