Repository TerryCavanagh/VVVVVV, pull requests merged in 2023-03, with the labels that each got.

#919 Unhardcoded glitchy and changing roomnames
  desktop_version/src/CustomLevels.cpp
  desktop_version/src/Finalclass.cpp
  desktop_version/src/Game.cpp
  desktop_version/src/Map.cpp
  desktop_version/src/Map.h
  desktop_version/src/Render.cpp
  desktop_version/src/RenderFixed.cpp
  desktop_version/src/RoomnameTranslator.cpp
  desktop_version/src/Script.cpp
Labels: enhancement, targets 2.4

#938 Fix possible dangling pointers in FontContainer.map_name_idx
  desktop_version/src/Font.cpp
Labels: required for 2.4

#940 Change `font::len`, `font::print` and `font::print_wrap` text argument from `std::string` to `const char*`
  desktop_version/src/Editor.cpp
  desktop_version/src/Font.cpp
  desktop_version/src/Font.h
  desktop_version/src/Graphics.cpp
  desktop_version/src/Render.cpp
  desktop_version/src/RoomnameTranslator.cpp
  desktop_version/src/Textbox.cpp
Labels: required for 2.4

#941 Fix hardestroom not being translated
  desktop_version/src/Game.cpp
Labels: required for 2.4

#947 Fix font .txt files not being null-terminated
  desktop_version/src/FileSystemUtils.cpp
  desktop_version/src/Font.cpp
Labels: required for 2.4

#948 Fix loading font .txt files that contain null bytes
  desktop_version/src/Font.cpp
Labels: required for 2.4

#949 Fix the game texture clearing during menu shaking
  desktop_version/src/Graphics.cpp
Labels: required for 2.4

#952 Fix textboxes fully fading out during blackout
  desktop_version/src/Render.cpp
Labels: required for 2.4

#956 Make Violet's button dialogue work in cutscene test
  desktop_version/lang/ca/cutscenes.xml
  desktop_version/lang/de/cutscenes.xml
  desktop_version/lang/en/cutscenes.xml
  desktop_version/lang/eo/cutscenes.xml
  desktop_version/lang/es/cutscenes.xml
  desktop_version/lang/fr/cutscenes.xml
  desktop_version/lang/it/cutscenes.xml
  desktop_version/lang/nl/cutscenes.xml
  desktop_version/lang/pt_BR/cutscenes.xml
  desktop_version/lang/pt_PT/cutscenes.xml
  desktop_version/lang/ru/cutscenes.xml
  desktop_version/lang/tr/cutscenes.xml
  desktop_version/src/LocalizationMaint.cpp
  desktop_version/src/Script.cpp
  desktop_version/src/Script.h
Labels: localization

#958 Fix box placement in editor
  desktop_version/src/Editor.cpp
Labels: required for 2.4

#961 Add button glyphs support to selection hint on language screen
  desktop_version/lang/ca/meta.xml
  desktop_version/lang/de/meta.xml
  desktop_version/lang/en/meta.xml
  desktop_version/lang/eo/meta.xml
  desktop_version/lang/es/meta.xml
  desktop_version/lang/fr/meta.xml
  desktop_version/lang/it/meta.xml
  desktop_version/lang/nl/meta.xml
  desktop_version/lang/pt_BR/meta.xml
  desktop_version/lang/pt_PT/meta.xml
  desktop_version/lang/ru/meta.xml
  desktop_version/lang/tr/meta.xml
  desktop_version/src/Localization.h
  desktop_version/src/LocalizationMaint.cpp
  desktop_version/src/LocalizationStorage.cpp
  desktop_version/src/Render.cpp
Labels: localization

#960 Show correct button glyph for interact if Enter/E are not split
  desktop_version/src/ButtonGlyphs.cpp
  desktop_version/src/Game.cpp
  desktop_version/src/Input.cpp
  desktop_version/src/Render.cpp
Labels: required for 2.4

#964 Make textbuttons() work for transparent text boxes
  desktop_version/src/Graphics.cpp
  desktop_version/src/Graphics.h
Labels: required for 2.4
