Repository TerryCavanagh/VVVVVV, pull requests merged in 2023-11, with the labels that each got.

#1048 Fix %cs showing instead of commit date on Windows (or older git?)
  desktop_version/version.cmake
Labels: targets 2.4

#1047 Use Android SDL2 via Maven
  .github/workflows/android.yml
  desktop_version/CMakeLists.txt
  desktop_version/VVVVVV-android/app/build.gradle
  desktop_version/VVVVVV-android/app/jni/CMakeLists.txt
  desktop_version/VVVVVV-android/app/jni/SDL
  desktop_version/VVVVVV-android/app/src/main/java/org/libsdl/app/HIDDevice.java
  desktop_version/VVVVVV-android/app/src/main/java/org/libsdl/app/HIDDeviceBLESteamController.java
  desktop_version/VVVVVV-android/app/src/main/java/org/libsdl/app/HIDDeviceManager.java
  desktop_version/VVVVVV-android/app/src/main/java/org/libsdl/app/HIDDeviceUSB.java
  desktop_version/VVVVVV-android/app/src/main/java/org/libsdl/app/SDL.java
  desktop_version/VVVVVV-android/app/src/main/java/org/libsdl/app/SDLActivity.java
  desktop_version/VVVVVV-android/app/src/main/java/org/libsdl/app/SDLAudioManager.java
  desktop_version/VVVVVV-android/app/src/main/java/org/libsdl/app/SDLControllerManager.java
  desktop_version/VVVVVV-android/app/src/main/java/org/libsdl/app/SDLSurface.java
  desktop_version/VVVVVV-android/build.gradle
Labels: targets 2.4

#1042 Change levelstats data type from vector to map (to fix inflated files)
  desktop_version/src/Game.cpp
  desktop_version/src/Game.h
Labels: required for 2.4

#1015 Translate hardest room at display time instead of at time of death
  desktop_version/src/Game.cpp
  desktop_version/src/Game.h
  desktop_version/src/Script.cpp
Labels: localization

#1063 Fix remaining audio speedup/slowdown bug
  desktop_version/src/Music.cpp
Labels: required for 2.4

#1062 Fix incorrect tiles in outside BG autotiling
  desktop_version/src/Editor.cpp
Labels: required for 2.4
