Repository TerryCavanagh/VVVVVV, pull requests merged in 2024-01, with the labels that each got.

#1041 Enable SDL_HINT_IME_SHOW_UI to make typing CJK not guesswork
  desktop_version/src/main.cpp
Labels: localization

#1095 Add a system for selecting between wordy/wordy2
  desktop_version/src/CWrappers.cpp
  desktop_version/src/CWrappers.h
  desktop_version/src/Localization.cpp
  desktop_version/src/Localization.h
  desktop_version/src/LocalizationStorage.cpp
  desktop_version/src/LocalizationStorage.h
  desktop_version/src/UtilityClass.cpp
  desktop_version/src/UtilityClass.h
  desktop_version/src/VFormat.c
Labels: localization

#1097 Remove hair spaces from Japanese translation
  desktop_version/lang/ja/strings.xml
Labels: localization

#1099 Fix another incorrect autotile
  desktop_version/src/Editor.cpp
Labels: required for 2.4

#1096 Indicate modes when loading in to gameplay
  desktop_version/src/Game.cpp
  desktop_version/src/Game.h
  desktop_version/src/Render.cpp
  desktop_version/src/RenderFixed.cpp
  desktop_version/src/Script.cpp
Labels: targets 2.4

#1101 Add support for right-aligned roomtext
  desktop_version/src/Editor.cpp
  desktop_version/src/Graphics.cpp
  desktop_version/src/Graphics.h
  desktop_version/src/Map.cpp
  desktop_version/src/Map.h
  desktop_version/src/Render.cpp
Labels: localization

#1121 Replace U+2013 (–) by standard dash in Ukrainian
  desktop_version/lang/uk/strings.xml
Labels: localization

#1122 Add support for GameCube glyphs
  desktop_version/fonts/buttons_10x10.fontmeta
  desktop_version/fonts/buttons_10x10.png
  desktop_version/fonts/buttons_12x12.fontmeta
  desktop_version/fonts/buttons_12x12.png
  desktop_version/fonts/buttons_8x8.fontmeta
  desktop_version/fonts/buttons_8x8.png
  desktop_version/src/ButtonGlyphs.cpp
Labels: localization

#1125 Fix segfault from attempting to unwordwrap a string that starts with two newlines
  desktop_version/src/Font.cpp
Labels: localization
