Repository TerryCavanagh/VVVVVV, pull requests merged in 2024-11, with the labels that each got.

#1203 Correctly set VVV_CXX_SRC flags (set_source_files_properties isn't cumulative)
  desktop_version/CMakeLists.txt
Labels: required for 2.5

#1207 CI: Migrate to SLR Sniper SDK for Linux builds
  .github/workflows/ci.yml
Labels: required for 2.5

#1137 iOS port (for desktop_version)
  desktop_version/AppIcon.xcassets/AppIcon.appiconset/AppIcon.png
  desktop_version/AppIcon.xcassets/AppIcon.appiconset/Contents.json
  desktop_version/AppIcon.xcassets/Contents.json
  desktop_version/CMakeLists.txt
  desktop_version/Info.plist
  desktop_version/VVVVVV-android/app/build.gradle
  desktop_version/src/ButtonGlyphs.cpp
  desktop_version/src/FileSystemUtils.cpp
  desktop_version/src/Game.cpp
  desktop_version/src/SDL_uikit_main.c
  desktop_version/src/Screen.cpp
  desktop_version/src/Vlogging.c
  desktop_version/src/main.cpp
Labels: enhancement, required for 2.5

#1210 Make 0-length gravity lines invisible again
  desktop_version/src/Graphics.cpp
Labels: required for 2.4
